name: LUcompute
channels:
    - defaults
    - conda-forge
dependencies:
    - python=3.6.2
    - numpy=1.13.1
    - scipy=0.19.1
    - sympy=1.1.1
    - ipywidgets=7.0.1
    - matplotlib=2.0.2
    - notebook=5.0.0
    - widgetsnbextension=3.0.2
